In [4]:
import kagglehub
from pathlib import Path 
# Download latest version
na_folder = Path(kagglehub.dataset_download("jasonairroi/airbnb-market-data-north-america"))
eu_folder = Path(kagglehub.dataset_download("jasonairroi/airbnb-market-data-europe"))
asia_pacific_folder = Path(kagglehub.dataset_download("jasonairroi/airbnb-market-data-asia-pacific"))
latin_caribbean_folder = Path(kagglehub.dataset_download("jasonairroi/airbnb-market-data-latin-america-caribbean"))

na_listings_path = na_folder / "listings.csv"
eu_listings_path = eu_folder / "listings.csv"
asia_pacific_listings_path = asia_pacific_folder / "listings.csv"
latin_caribbean_listings_path = latin_caribbean_folder / "listings.csv"

na_past_rates_path = na_folder / "past_rates.csv"
eu_past_rates_path = eu_folder / "past_rates.csv"
asia_pacific_past_rates_path = asia_pacific_folder / "past_rates.csv"
latin_caribbean_past_rates_path = latin_caribbean_folder / "past_rates.csv"

In [12]:
import pandas as pd
import numpy as np



na_listings = pd.read_csv(na_listings_path, sep=None, engine="python", on_bad_lines="skip")
eu_listings = pd.read_csv(eu_listings_path, sep=None, engine="python", on_bad_lines="skip")
asia_pacific_listings = pd.read_csv(asia_pacific_listings_path, sep=None, engine="python", on_bad_lines="skip")
latin_caribbean_listings = pd.read_csv(latin_caribbean_listings_path, sep=None, engine="python", on_bad_lines="skip")

na_past_rates = pd.read_csv(na_past_rates_path, sep=None, engine="python", on_bad_lines="skip")
eu_past_rates = pd.read_csv(eu_past_rates_path, sep=None, engine="python", on_bad_lines="skip")
asia_pacific_past_rates = pd.read_csv(asia_pacific_past_rates_path, sep=None, engine="python", on_bad_lines="skip")
latin_caribbean_past_rates = pd.read_csv(latin_caribbean_past_rates_path, sep=None, engine="python", on_bad_lines="skip")

na_listings["Region"] = "North America"
eu_listings["Region"] = "Europe"
asia_pacific_listings["Region"] = "Asia-Pacific"
latin_caribbean_listings["Region"] = "Latin America/Caribbean"

na_past_rates["Region"] = "North America"
eu_past_rates["Region"] = "Europe"
asia_pacific_past_rates["Region"] = "Asia-Pacific"
latin_caribbean_past_rates["Region"] = "Latin America/Caribbean"

all_listings = pd.concat([na_listings, eu_listings, asia_pacific_listings, latin_caribbean_listings], ignore_index=True)
all_past_rates = pd.concat([na_past_rates, eu_past_rates, asia_pacific_past_rates, latin_caribbean_past_rates], ignore_index=True)

In [13]:
all_listings.head()

,listing_id,listing_type,room_type,cover_photo_url,photos_count,host_id,superhost,latitude,longitude,guests,...,l90d_adjusted_revpar,l90d_adjusted_revpar_native,l90d_reserved_days,l90d_blocked_days,l90d_available_days,l90d_total_days,country,state,city,Region
0,177833,Entire guesthouse,entire_home,https://a0.muscache.com/im/pictures/67280846-0...,36.0,c40416107927,True,38.9043,-104.973,3.0,...,0.0,0.0,8.0,0.0,82.0,90.0,United States,Colorado,Colorado Springs,North America
1,312996,Entire guesthouse,entire_home,https://a0.muscache.com/im/pictures/hosting/Ho...,34.0,62fb4136b324,True,38.8388,-104.814,2.0,...,49.5,49.5,35.0,14.0,55.0,90.0,United States,Colorado,Colorado Springs,North America
2,2237908,Entire rental unit,entire_home,https://a0.muscache.com/im/pictures/0e03770a-3...,15.0,13c8856ce8b1,True,38.8413,-104.8097,5.0,...,0.0,0.0,48.0,0.0,42.0,90.0,United States,Colorado,Colorado Springs,North America
3,2306147,Entire home,entire_home,https://a0.muscache.com/im/pictures/miso/Hosti...,16.0,8fe96865f520,True,38.8456,-104.7298,7.0,...,0.0,0.0,34.0,0.0,56.0,90.0,United States,Colorado,Colorado Springs,North America
4,2526116,Entire home,entire_home,https://a0.muscache.com/im/pictures/hosting/Ho...,39.0,d127f1078650,True,38.8368,-104.8437,8.0,...,0.0,0.0,40.0,0.0,50.0,90.0,United States,Colorado,Colorado Springs,North America

In [14]:
all_past_rates.head()

,listing_id,date,vacant_days,reserved_days,occupancy,revenue,rate_avg,booked_rate_avg,booking_lead_time_avg,length_of_stay_avg,min_nights_avg,native_booked_rate_avg,native_rate_avg,native_revenue,country,state,city,Region
0,13117492,2025-02-01,4,24,0.857,1283.0,53.4,53.5,3.0,6.0,2.0,27022.0,26972.0,648031.0,Costa Rica,Limón Province,Cahuita,North America
1,13117492,2025-03-01,15,16,0.516,874.0,54.4,54.6,18.0,3.0,2.0,27693.0,27591.0,443283.0,Costa Rica,Limón Province,Cahuita,North America
2,13117492,2025-04-01,9,21,0.700,1125.0,53.6,53.6,38.0,7.0,2.0,26822.0,26822.0,562972.0,Costa Rica,Limón Province,Cahuita,North America
3,13117492,2025-05-01,31,0,0.000,0.0,52.2,NaN,NaN,NaN,1.0,NaN,26446.0,0.0,Costa Rica,Limón Province,Cahuita,North America
4,13117492,2025-06-01,30,0,0.000,0.0,60.3,NaN,NaN,NaN,1.0,NaN,30576.0,0.0,Costa Rica,Limón Province,Cahuita,North America